part with render films according choose sort type
htmlacademy-ecmascript/132653-cinemaddict-12 pull request #8
Opened 2020-08-30 10:17 UTC by aalexceenko

2020-08-30 10:20 UTC, aalexceenko commented on src/main.js
> +// const sort = new SortView().getElement();
вот тут я объявила переменную, на которой буду ловить событие

2020-08-30 10:20 UTC, aalexceenko commented on src/main.js
> +// sort.addEventListener(`click`, sortTypeChangeHandler);
но это событие не срабатывает

2020-08-30 10:20 UTC, aalexceenko commented on src/main.js
> +document.querySelector(`.sort`).addEventListener(`click`, sortTypeChangeHandler);
а вот так все работает, хотя это тот же самый элемент

2020-08-30 19:28 UTC, trave requested changes

2020-08-30 19:28 UTC, trave commented on src/main.js
> +// const sort = new SortView().getElement();
`new SortView() !== new SortView()` Оператор `new` каждый раз создаёт похожий, но не такой же объект. У тебя на 26-ой строке создаётся объект SortView и ренедрится, а здесь ты создаешь новый, но не рендеришь его и пытаешься подписаться на его события. Но клики пользователь делает по SortView созданному на 26-ой строке. Отсюда боль.

2020-08-30 19:28 UTC, trave commented on src/main.js
> +const sortFilms = (sortType) => {
Сортировкой должен заниматься компонент отвечающий за предстваление фильмов, а не main.js.

2020-08-30 19:28 UTC, trave commented on src/main.js
> +// sort.addEventListener(`click`, sortTypeChangeHandler);
Ответил выше.

2020-08-30 19:28 UTC, trave commented on src/main.js
> +document.querySelector(`.sort`).addEventListener(`click`, sortTypeChangeHandler);
Ответил выше. Здесь работает потому как через querySelector ты запрашиваешь элемент принадлежащий отрендеренному SortView, а не тому элемент которого положила в `sort` переменную.

2020-08-30 19:28 UTC, trave commented on src/main.js
> +let films = new Array(FILM_COUNT).fill().map(generateFilm);
Переноси саму сортировку в презентер, а в main.js оставь только связывание компонента отображающего сортировку(и принимающего выбор пользоватем сортировки). Т.е. событие выбора сортировки происходит в SortView, main.js ловит это событие и передаёт в презентер, который в соответствии с выбором переданным типом сортировки рисует фильмы.

2020-08-31 19:32 UTC, trave commented on src/view/sort.js
> +      evt.target.classList.add(`sort__button--active`);
Нужно вынести за цикл обхода элементов. Иначе ты на каждую итерацию пытаешься добавить класс, хотя это нужно делать только один раз.

2020-08-31 19:32 UTC, trave commented on src/presenter/films-container.js
> +    this._renderedFilmCount = FILM_COUNT_PER_STEP;
Оно может и работает, но и работает, но не совсем честно. Метод занимается очисткой и на предидущей строке ты удалила ВСЕ ранее отрендеренные фильмы, а тут устанавливаешь счётчик отрендеренных фильмов в какое-то число отличное от 0.

Правильно здесь сбрасывать счётчик в 0, а там где ты непосредственно рендеришь первую порцию ифльмов устанавливать счётчик в FILM_COUNT_PER_STEP или другое число которое действительно отрендерено (на строке 160).

2020-08-31 19:32 UTC, merged